JOB_DESCRIPTIONS = {
    "HR": "Human Resources professionals manage employee relations, recruitment, training, and company culture, ensuring a productive and compliant workplace.",
    "DESIGNER": "Designers create visual concepts using software or by hand to communicate ideas that inspire, inform, and captivate consumers.",
    "INFORMATION-TECHNOLOGY": "IT professionals oversee computer systems, software, networks, and technical infrastructure to ensure seamless organizational operations.",
    "TEACHER": "Teachers educate and inspire students, developing lesson plans, assessing progress, and fostering a positive learning environment.",
    "ADVOCATE": "Advocates and legal professionals provide legal counsel, represent clients in proceedings, and ensure adherence to the rule of law.",
    "BUSINESS-DEVELOPMENT": "Business Development experts focus on strategic growth, building partnerships, expanding market reach, and driving revenue.",
    "HEALTHCARE": "Healthcare professionals provide medical care, promote wellness, and manage patient health in clinics, hospitals, and communities.",
    "FITNESS": "Fitness experts guide individuals in achieving physical health goals through customized exercise, nutrition, and wellness programs.",
    "AGRICULTURE": "Agriculture professionals manage farming, crop production, and livestock, utilizing scientific principles to optimize food yield.",
    "SALES": "Sales experts drive revenue by building client relationships, negotiating contracts, and closing deals for products or services.",
    "CONSULTANT": "Consultants provide expert advice in specific fields, helping organizations solve problems, improve performance, and maximize growth.",
    "DIGITAL-MEDIA": "Digital Media specialists create, manage, and optimize digital content and campaigns to engage audiences and build brand presence.",
    "CHEF": "Chefs oversee kitchen operations, create innovative menus, and ensure the preparation of high-quality culinary dishes.",
    "FINANCE": "Finance professionals manage financial planning, analysis, investment strategies, and corporate accounting to ensure economic stability.",
    "APPAREL": "Apparel professionals work in fashion design, merchandising, and production, keeping up with trends to create consumer clothing.",
    "ENGINEERING": "Engineers apply scientific and mathematical principles to design, build, and maintain complex structures, machines, and systems.",
    "ACCOUNTANT": "Accountants prepare and examine financial records, ensuring accuracy, tax compliance, and transparent financial reporting.",
    "CONSTRUCTION": "Construction professionals manage and execute building projects, ensuring safety, structural integrity, and architectural compliance.",
    "PUBLIC-RELATIONS": "PR specialists maintain a positive public image for clients, managing media relations, press releases, and strategic communications.",
    "BANKING": "Banking professionals handle financial transactions, asset management, risk assessment, and customer financial services.",
    "ARTS": "Artists and creative professionals produce original works of art, spanning visual, performing, and literary disciplines to evoke emotion.",
    "AVIATION": "Aviation professionals operate and manage aircraft, coordinate flight logistics, and ensure rigorous safety standards in aerospace."
}
